### ISSUE TITLE
Changing the owner of a task with DW "Anteater" doesnt show in tasklist

### ISSUE THREAD

**Issue by DjSlash** [dokufreaks/plugin-task#18]
When we change the owner of a task, it doesn't change it on the tasklist. I'm sure this wasn't an issue before, so I'm guessing it has something to do with the newer DW version. Since I'm not really into the DW (plugin) code, I don't know where to start looking for a fix.

**Comment by Klap-in** [comment]
Fixed by 0f455d706ff644d92e9746e772fbb733a67261c2
