### ISSUE TITLE
ACL

### ISSUE THREAD

**Issue by Flametail** [dokufreaks/plugin-task#21]
I am using task to try to organize some tasks for my team.
From an admin perspective, all is well. Everything works.

From a team perspective, ACL i denying access, with the fabled ACL Not set up, denying access to everyone.

The problem with that, though, is that I have triple checked my ACL and there is no issue there.

This only happens with task, and only on the pages where is lists the tasks.

The actually task pages are fine, and the team has full access to them, but the lists are getting ACL'd

**Comment by LarsGit223** [comment]
Should now be fixed in current master.
