### ISSUE TITLE
Screenshot Links Broken

### ISSUE THREAD

**Issue by nine-patrickhe** [dokufreaks/plugin-task#29]
The screenshots found at https://www.dokuwiki.org/plugin:task#screenshots seem to be deleted from the image hoster.

**Comment by xrat** [comment]
Thanks for reporting this. The screenshots were done by me, and they were hosted on a free image hoster who recently changed policies. In fact, I lost all images of this account. However, they were anyway outdated and should be replaced with screenshots showing the current DW default theme. Unfortunately, currently, I have no installation available with the default theme.

**Comment by LarsGit223** [comment]
I added new screenshots to the github repository. I hope that these are acceptable. If there are any suggestions for improvement, please let me know (and re-open issue).
