### ISSUE TITLE
Feature Request: Linking to Redmine Tickets

### ISSUE THREAD

**Issue by therequest** [dokufreaks/plugin-task#30]
I love the Task Tool, it is simple and works great.

I also would like the option, to link to redmine issues or getting my issues via the redmine api (maybe a look at the redissue plugins helps)..

That would turn your great tool into an fantastic tool :)

well there is one other point:
if i switch the plugin to the user dropdown list -> this does not work with ldap-users, maybe there is a way to fix this

**Comment by Klap-in** [comment]
(please report one issue per issue. Thanks)

**Comment by LarsGit223** [comment]
If the Redissue plugin is already displaying redmine issues than what do you need the task plugin for?

If it is only for having a list of redmine issues than I would say it is better to be implemented in the redissue plugin. That could fetch redmine issues into a list and use the pagelist plugin to display it (like the task plugin is using the pagelist plugin to display it's task list).

**Comment by therequest** [comment]
redissue sucks and is slow on requests and i love the task plugin...
i‘ve just created the needed plugin on myself so we can close

**Comment by LarsGit223** [comment]
:+1:
